#!/bin/bash

PROMPT='%M@%n → %~ $(git_prompt_info)'
RPROMPT='%? - %D/%@'

ZSH_THEME_GIT_PROMPT_PREFIX=" pregit:"
ZSH_THEME_GIT_PROMPT_SUFFIX="sufgit"
ZSH_THEME_GIT_PROMPT_DIRTY="dirgit"
ZSH_THEME_GIT_PROMPT_CLEAN="clegit"

ZSH_THEME_GIT_PROMPT_ADDED="add"
ZSH_THEME_GIT_PROMPT_MODIFIED="mod"
ZSH_THEME_GIT_PROMPT_DELETED="del"
ZSH_THEME_GIT_PROMPT_RENAMED="mv"
ZSH_THEME_GIT_PROMPT_UNMERGED="um"
ZSH_THEME_GIT_PROMPT_UNTRACKED="ut"
